# Generated by Django 6.0.1 on 2026-02-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_submission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autograderun',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rubric'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rubric'),
        ),
    ]
